AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Processor
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ImageProcessorStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.image.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://img-processor-s3/537cb45f67f1b563ff343af32bb20a93
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  ImageProcessorStoreApi:
    Description: healthcheck URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/image/health
    Export:
      Name: ImageProcessor
