AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Processor

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  ImageProcessorStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.image.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/image-processor-0.0.1-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ImageProcessorStoreApi:
    Description: healthcheck URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/image/health'
    Export:
      Name: ImageProcessor